return {
	"nvim-treesitter/nvim-treesitter",
	cmd = "TSUpdate",
	opts = {
		auto_install = true,
		indent = { enable = true }, ---@type lazyvim.TSFeat
		highlight = { enable = true, additional_vim_regex_highlighting = false }, ---@type lazyvim.TSFeat
		folds = { enable = true }, ---@type lazyvim.TSFeat
		-- A list of parser names, or "all" (the listed parsers MUST always be installed)
		ensure_installed = {
			"bash",
			"c",
			"css",
			"dart",
			"diff",
			"gitignore",
			"go",
			"gomod",
			"gosum",
			"graphql",
			"html",
			"javascript",
			"jsdoc",
			"json",
			"jsonc",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"printf",
			"python",
			"query",
			"regex",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"vue",
			"xml",
			"yaml",
		},
	},
}
